#!/bin/bash
#

#################################
echo 0 > /proc/sys/net/ipv4/ip_forward
######################################

######################################
iptables -Z  
iptables -F  
iptables -X 
iptables -t nat -Z
iptables -t nat -F
iptables -t nat -X
######################################

##########################################################
echo 1 > /proc/sys/net/ipv4/tcp_syncookies          # Syn Flood (DoS)
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts  # Port scanners
echo 0 > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses      # Sem resposta remota
for i in  /proc/sys/net/ipv4/conf/*; do
echo 0 > $i/accept_redirects                # Sem redirecionar rotas
echo 0 > $i/accept_source_route            # Sem traceroute
echo 1 > $i/log_martians                # Loga pacotes suspeitos no kernel
echo 1 > $i/rp_filter                  # Ip Spoofing
echo 1 > $i/secure_redirects; done                      # Redirecionamento seguro de pacotes
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all        # Sem ping e tracert
##########################################################

######################
iptables  -P  INPUT DROP  
iptables  -P  FORWARD DROP
iptables  -P  OUTPUT ACCEPT
######################

# Liberando a Loopback
####################
iptables -A  INPUT -i lo -j ACCEPT
####################

## Regras de segurança na internet e acessos
#####################################
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -m state --state NEW !  -i  venet0:0 -j DROP    
iptables -A FORWARD -m state --state NEW ! -i venet0:0 -j DROP
iptables -A INPUT -m state --state INVALID -j DROP
iptables -A FORWARD -m state --state INVALID -j DROP
#####################################

###########################################
iptables -t nat -A PREROUTING -i venet0 -p tcp --dport 80 -j REDIRECT --to-port 3128 
iptables -t nat -A POSTROUTING -o venet0:0 -j MASQUERADE 
###########################################

#

iptables -A INPUT -i venet0:0 -p icmp --icmp-type echo-request -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i venet0:0 -p tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i venet0:0 -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i venet0:0 -p tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i venet0:0 -p tcp --dport 21 -m state --state NEW,ESTABLISHED -j ACCEPT

#

##########################
echo 1 > /proc/sys/net/ipv4/ip_forward
##########################




